# .github/dependabot.yml
version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"

  # 2. Python Dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      python-minor-patch:
        update-types: ["minor", "patch"]
        patterns: ["*"]
